easy_admin:
  entities:
    Menu:

      class: App\Entity\Menu
      label: Menu

      form:
        fields:
          - { property: 'name' }
          - { property: 'slug' }
          - { property: 'list', type: 'App\Form\MenuType' }